# 2022 version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask-hello
        image: amullme/flask-hello
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: flask-hello
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000