apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  externalIPs:
  - 10.0.0.9
  selector:
    app: hello
  type: NodePort  
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007