Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.synced_folder "../../components/", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "10.0.0.10 testvm" >> /etc/hosts
    echo "10.0.0.11 prodvm" >> /etc/hosts
  SHELL
  config.vm.provision "shell", path: "../docker/docker_install.sh"

  # Define the test vm
  config.vm.define "testvm" do |testvm|
    testvm.vm.hostname = "testvm"
    testvm.vm.network "private_network", ip: "10.0.0.10"
  end

  # Define the stage vm
  config.vm.define "prodvm" do |prodvm|
    prodvm.vm.hostname = "prodvm"
    prodvm.vm.network "private_network", ip: "10.0.0.11"
  end

end 